name: Bug Report
description: Report an issue with the Postman platform.
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the issue you encountered. Duplicate issues will be closed. [Github Issue Tracker](https://github.com/postmanlabs/postman-app-support/issues)
    options:
    - label: I have searched the tracker for existing similar issues and I know that duplicates will be closed
      required: true
- type: textarea
  attributes:
    label: Describe the Issue
    description: |
      A high-level summary or description of the problem that you're facing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: A list of steps that can be followed to recreate the issue.
    placeholder: |
      1. Open a new request tab
      2. Select the Body tab
      3. Select the `raw` type 
      4. See error message...
  validations:
    required: true
- type: markdown
  attributes:
    value: '> **Tip**: You can attach images and recordings to textareas by dragging in the files. More visual examples will help us to understand the issue.'
- type: textarea
  attributes:
    label: Screenshots or Videos
    description: | 
      If you are reporting a UI based issue, please include screenshots or a short video to help visually explain the problem.
      Ensure that the screenshots/videos are full screen and do not contain any sensitive information such as API keys or Access Tokens. 
  validations:
    required: false
- type: dropdown
  attributes:
    label: Operating System
    description: Which OS are you using?
    options:
      - Windows
      - macOS
      - Linux
  validations:
    required: true
- type: input
  attributes:
    label: Postman Version
    description: Which version of the platform are you using? This can be found in 'General Settings > Settings > About'.
    placeholder: "10.12.0"
  validations:
    required: true
- type: dropdown
  attributes:
    label: Postman Platform
    description: Which Postman platform are you using?
    options:
      - Postman App
      - Postman Web
      - Postman VSCode Extension 
      - Both Postman App and Web
      - Other
  validations:
    required: true
- type: dropdown
  attributes:
    label: User Account Type
    description: Are you using Postman as a signed in or signed out user?
    options:
      - Signed In User
      - Signed Out User
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Context?
    description: |
      Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.
      You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
